### ISSUE TITLE
Check css pseudo class behavior (:valid, :invalid)

### ISSUE THREAD

**Issue by CaptainCodeman** [CaptainCodeman/svelte-form-helper#5]
These should ~correspond to validation messages being shown~ be applied if the form has been touched, but regular forms don't have the "only if touched" concept for the CSS, so we may need to add our own style class too that can be added to the inputs to enable:

```css
input.touched:valid {
	border-color: green;
}

input.touched:invalid {
	border-color: red;
}
```

Class name? `touched`, `validated`, `show`, `hint`? (maybe configurable option on the form / fields)
